name: halium-initramfs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialize environment
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static debootstrap -y

      - name: Build initramfs
        run: sudo ARCH=${{ matrix.arch }} ./build-initrd.sh
